server:
  address: localhost
  port: 8083

eureka:
  instance:
    client: 
      serviceUrl: 
        defaultZone: http://localhost:8761/eureka
    preferIpAddress: true
  
spring:
  application:
    name: account
  profiles:
    active: dev  
  config:
    import: optional:configserver:http://localhost:8888
