server:
  address: localhost
  port: 8082

eureka:
  instance:
    client: 
      serviceUrl: 
        defaultZone: http://localhost:8761/eureka
    preferIpAddress: true

spring:
  application:
    name: user
  config:
    import: optional:configserver:http://localhost:8888

management:
  server:
    address: localhost
    port: 8092
  endpoints:
    web:
      exposure:
        include: health, prometheus
