server:
  address: localhost
  port: 8082

eureka:
  instance:
    client: 
      serviceUrl: 
        defaultZone: http://localhost:8761/eureka
    preferIpAddress: true

spring:
  application:
    name: user
  profiles:
    active: dev 
  config:
    import: optional:configserver:http://localhost:8888
