server:
  port: 8081

eureka:
  instance:
    client: 
      serviceUrl: 
        defaultZone: http://localhost:8761/eureka
    preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: accountsModule
          uri: http://localhost:8083/
          predicates:
            - Path=/accounts/**
        - id: userModule
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**
  config:
    import: optional:configserver:http://localhost:8888

